#!/usr/bin/env python3
"""
Generate the GitBook API reference from NumPy-style docstrings.
"""

import argparse
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path

from griffe import DocstringSectionKind, load

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src'
DOCS = ROOT / 'docs' / 'api-reference'
GENERATED_NOTICE = '<!-- Generated by tools/generate_api_docs.py. Do not edit directly. -->'
PUBLIC_DUNDERS = {
    '__call__',
    '__enter__',
    '__exit__',
    '__getitem__',
    '__len__',
    '__matmul__',
}


@dataclass(frozen=True)
class Symbol:
    module: str
    name: str
    public_module: str | None = None

    @property
    def path(self):
        """
        Return the symbol's public import path.
        """
        return f'{self.public_module or self.module}.{self.name}'


@dataclass(frozen=True)
class Page:
    output: str
    title: str
    introduction: str
    symbols: tuple[Symbol, ...]


def symbols(module, *names, public_module=None):
    """
    Construct a tuple of documented symbols from one module.
    """
    return tuple(Symbol(module, name, public_module) for name in names)


PAGES = (
    Page(
        'core.md',
        'Core types',
        'Core image containers, spatial geometry, transformations, and metadata models.',
        symbols(
            'imzdesk.core',
            'DImage',
            'PairedImage',
            'RImage',
            'RaggedTensor',
            'SImage',
            'SpatialImage',
            'Geometry',
            'Transform',
            'Metadata',
        )
        + symbols(
            'imzdesk.core.metadata',
            'BoundingBox',
            'Dimensions',
        ),
    ),
    Page(
        'data.md',
        'Datasets',
        'Dataset manifests and map-style dataset loading.',
        symbols('imzdesk.data', 'Dataset', 'DatasetManifest'),
    ),
    Page(
        'io.md',
        'Image input and output',
        'Readers for whole-slide images and imzML mass spectrometry images.',
        symbols('imzdesk.io', 'ImageBase', 'MSI', 'WSI'),
    ),
    Page(
        'registration.md',
        'Registration',
        'Functions for registering MSI acquisitions to whole-slide images.',
        symbols(
            'imzdesk.registration',
            'register',
            'apply_wsi_crop_offset',
            'centroid',
            'centroid_initialization',
            'rotation_sweep',
            'chamfer_refine',
            'chamfer_loss',
            'contour',
            'warp',
            'iou',
            'ncc',
        ),
    ),
    Page(
        'visualization.md',
        'Visualization',
        'Utilities for displaying dense image data.',
        symbols('imzdesk.visualization', 'DImageDisplay'),
    ),
    Page(
        'transforms/composition.md',
        'Composition and conversion',
        'Base classes and transforms for composing pipelines and converting outputs.',
        symbols(
            'imzdesk.transforms',
            'Transform',
            'Compose',
            'Parallel',
            'RandomApply',
            'RandomChoice',
            'ToTensor',
        ),
    ),
    Page(
        'transforms/geometry.md',
        'Geometry transforms',
        'Transforms that change an image grid, extent, orientation, or resolution.',
        symbols(
            'imzdesk.transforms',
            'ToImage',
            'CenterCrop',
            'Pad',
            'RandomAffine',
            'RandomHorizontalFlip',
            'RandomResizedCrop',
            'RandomRotate90',
            'RandomVerticalFlip',
            'Resample',
            'Resize',
            'RandomCrop',
        ),
    ),
    Page(
        'transforms/intensity.md',
        'Intensity transforms',
        'Transforms that change pixel or channel intensity without changing the image grid.',
        symbols(
            'imzdesk.transforms',
            'ChannelNormalize',
            'ColorJitter',
            'GaussianBlur',
            'RandomErasing',
            'OpticalDensity',
            'Threshold',
        ),
    ),
    Page(
        'transforms/msi.md',
        'MSI processing transforms',
        'Transforms for reading, normalizing, embedding, and densifying mass spectra.',
        symbols(
            'imzdesk.transforms',
            'ToRImage',
            'Embed',
            'Bin',
            'Scale',
            'TIC',
            'Normalize',
            'ToDense',
        ),
    ),
    Page(
        'transforms/reduction.md',
        'Reduction transforms',
        'Transforms that reduce multichannel data for analysis or visualization.',
        symbols('imzdesk.transforms', 'NMF', 'PCA', 'Project', 'TSNE'),
    ),
)


_modules = {}
EXPORT_MODULES = {
    'imzdesk.core',
    'imzdesk.data',
    'imzdesk.io',
    'imzdesk.transforms',
    'imzdesk.visualization',
}


def load_module(name):
    """
    Load and cache a module for static documentation analysis.
    """
    if name not in _modules:
        _modules[name] = load(
            name,
            search_paths=[SOURCE],
            docstring_parser='numpy',
        )
    return _modules[name]


def resolve(symbol):
    """
    Resolve a configured symbol to its defining Griffe object.
    """
    try:
        member = load_module(symbol.module)[symbol.name]
    except KeyError as exception:
        raise RuntimeError(f'Could not find documented symbol {symbol.path}.') from exception
    return member.target if member.is_alias else member


def clean_inline(value):
    """
    Normalize inline reStructuredText for Markdown output.
    """
    if value is None:
        return ''
    text = str(value).strip().replace('``', '`')
    return re.sub(r'\s+', ' ', text)


def clean_text(value):
    """
    Normalize wrapped docstring prose while preserving paragraphs.
    """
    paragraphs = re.split(r'\n\s*\n', str(value).strip())
    return '\n\n'.join(
        textwrap.fill(clean_inline(paragraph), width=80)
        for paragraph in paragraphs
        if paragraph.strip()
    )


def annotation(value):
    """
    Return a normalized display value for a type expression.
    """
    if type(value).__name__ == 'ExprTuple':
        elements = []
        for element in value.elements:
            item = clean_inline(element)
            literal = item in {'None', 'True', 'False'} or item.replace('.', '', 1).isdigit()
            elements.append(item if literal else repr(item))
        return f'{{{", ".join(elements)}}}'
    return (clean_inline(value) or 'Any').replace(' - ', '-')


def signature_line(object_, path, *, class_=False):
    """
    Format a public path with an object's source signature.
    """
    signature = object_.signature()
    opening = signature.find('(')
    parameters = signature[opening:] if opening >= 0 else ''
    prefix = 'class ' if class_ else ''
    line = f'{prefix}{path}{parameters}'
    if len(line) <= 80 or not parameters:
        return line

    arguments = split_arguments(parameters[1:-1])
    if len(arguments) <= 1:
        return line
    body = ',\n'.join(f'    {argument}' for argument in arguments)
    return f'{prefix}{path}(\n{body},\n)'


def split_arguments(parameters):
    """
    Split a signature argument list without splitting nested expressions.
    """
    if not parameters:
        return []
    arguments = []
    start = 0
    depth = 0
    quote = None
    escaped = False
    for index, character in enumerate(parameters):
        if quote is not None:
            if escaped:
                escaped = False
            elif character == '\\':
                escaped = True
            elif character == quote:
                quote = None
            continue
        if character in {'\'', '"'}:
            quote = character
        elif character in '([{':
            depth += 1
        elif character in ')]}':
            depth -= 1
        elif character == ',' and depth == 0:
            arguments.append(parameters[start:index].strip())
            start = index + 1
    arguments.append(parameters[start:].strip())
    return [argument for argument in arguments if argument]


def docstring_for(object_):
    """
    Return an object's docstring or its constructor docstring.
    """
    if object_.docstring is not None:
        return object_.docstring
    if object_.is_class and '__init__' in object_.members:
        return object_.members['__init__'].docstring
    return None


def render_list_section(title, values, *, include_name=True):
    """
    Render a structured docstring section as a Markdown list.
    """
    lines = [f'**{title}**', '']
    for value in values:
        name = clean_inline(getattr(value, 'name', ''))
        type_name = annotation(getattr(value, 'annotation', None))
        description = clean_inline(getattr(value, 'description', ''))
        if include_name and name:
            subject = f'`{name}` (`{type_name}`)'
        else:
            subject = f'`{type_name}`'
        item = f'- {subject}: {description}' if description else f'- {subject}'
        lines.extend(textwrap.wrap(item, width=80, subsequent_indent='  ', break_long_words=False))
    lines.append('')
    return lines


def render_docstring(docstring, *, skip_attributes=False):
    """
    Render parsed NumPy docstring sections as Markdown.
    """
    if docstring is None:
        return []
    lines = []
    for section in docstring.parsed:
        kind = section.kind
        if kind is DocstringSectionKind.text:
            text = clean_text(section.value)
            if text:
                lines.extend([text, ''])
        elif kind in {DocstringSectionKind.parameters, DocstringSectionKind.other_parameters}:
            lines.extend(render_list_section('Parameters', section.value))
        elif kind is DocstringSectionKind.attributes:
            if not skip_attributes:
                lines.extend(render_list_section('Attributes', section.value))
        elif kind is DocstringSectionKind.raises:
            lines.extend(render_list_section('Raises', section.value, include_name=False))
        elif kind is DocstringSectionKind.warns:
            lines.extend(render_list_section('Warnings', section.value, include_name=False))
        elif kind is DocstringSectionKind.returns:
            lines.extend(render_list_section('Returns', section.value))
        elif kind is DocstringSectionKind.yields:
            lines.extend(render_list_section('Yields', section.value))
        elif kind is DocstringSectionKind.admonition:
            title = section.title or 'Note'
            description = clean_text(section.value.description)
            lines.extend([f'**{title}**', '', description, ''])
        else:
            raise RuntimeError(f'Unsupported docstring section: {kind.value}.')
    return lines


def documented_members(class_):
    """
    Yield documented public methods and properties from a class.
    """
    for name, member in class_.members.items():
        if name == '__init__':
            continue
        if name.startswith('_') and name not in PUBLIC_DUNDERS:
            continue
        if member.kind.value == 'function' or 'property' in member.labels:
            if member.docstring is None:
                raise RuntimeError(f'Public member {class_.path}.{name} has no docstring.')
            yield name, member


def render_fields(class_):
    """
    Render explicitly annotated class and instance fields.
    """
    fields = [
        (name, member)
        for name, member in class_.members.items()
        if not name.startswith('_')
        and member.kind.value == 'attribute'
        and 'property' not in member.labels
        and member.annotation is not None
    ]
    if not fields:
        return []

    descriptions = {}
    docstring = docstring_for(class_)
    if docstring is not None:
        for section in docstring.parsed:
            if section.kind is DocstringSectionKind.attributes:
                descriptions.update({value.name: clean_inline(value.description) for value in section.value})

    lines = ['**Fields**', '']
    for name, field in fields:
        type_name = annotation(field.annotation)
        description = descriptions.get(name, '')
        subject = f'`{name}` (`{type_name}`)'
        item = f'- {subject}: {description}' if description else f'- {subject}'
        lines.extend(textwrap.wrap(item, width=80, subsequent_indent='  ', break_long_words=False))
    lines.append('')
    return lines


def render_member(public_class_path, name, member):
    """
    Render one class method or property.
    """
    lines = [f'### {name}', '']
    path = f'{public_class_path}.{name}'
    if 'property' in member.labels:
        lines.extend(['```text', f'property {path}', '```', ''])
    else:
        qualifiers = []
        if 'classmethod' in member.labels:
            qualifiers.append('classmethod')
        if 'staticmethod' in member.labels:
            qualifiers.append('staticmethod')
        if 'abstractmethod' in member.labels:
            qualifiers.append('abstract')
        line = signature_line(member, path)
        if qualifiers:
            line = f'{", ".join(qualifiers)} {line}'
        lines.extend(['```text', line, '```', ''])
    lines.extend(render_docstring(member.docstring))
    return lines


def render_symbol(symbol):
    """
    Render one configured public symbol and its members.
    """
    object_ = resolve(symbol)
    lines = [f'## {symbol.name}', '', '```text']
    if object_.is_class:
        lines.append(signature_line(object_, symbol.path, class_=True))
    elif object_.is_function:
        lines.append(signature_line(object_, symbol.path))
    else:
        raise RuntimeError(f'Unsupported symbol kind for {symbol.path}: {object_.kind.value}.')
    lines.extend(['```', ''])

    docstring = docstring_for(object_)
    if docstring is None:
        raise RuntimeError(f'Public symbol {symbol.path} has no docstring.')
    fields = render_fields(object_) if object_.is_class else []
    lines.extend(render_docstring(docstring, skip_attributes=bool(fields)))

    if object_.is_class:
        lines.extend(fields)
        for name, member in documented_members(object_):
            lines.extend(render_member(symbol.path, name, member))
    return lines


def render_page(page):
    """
    Render one configured API reference page.
    """
    lines = [GENERATED_NOTICE, '', f'# {page.title}', '', clean_text(page.introduction), '']
    for symbol in page.symbols:
        lines.extend(render_symbol(symbol))
    return '\n'.join(lines).rstrip() + '\n'


def render_index():
    """
    Render the API reference landing page.
    """
    return f'''{GENERATED_NOTICE}

# API reference

The API reference documents the supported public Python interface outside
`imzdesk.server`. The pages are generated from NumPy-style docstrings in the
source code.

## Packages

- [Core types](core.md)
- [Datasets](data.md)
- [Image input and output](io.md)
- [Registration](registration.md)
- [Visualization](visualization.md)
- [Transforms](transforms/README.md)
'''


def render_transforms_index():
    """
    Render the transforms landing page.
    """
    return f'''{GENERATED_NOTICE}

# Transforms

Transforms convert image data, change its spatial or intensity representation,
and compose preprocessing pipelines.

## Transform groups

- [Composition and conversion](composition.md)
- [Geometry transforms](geometry.md)
- [Intensity transforms](intensity.md)
- [MSI processing transforms](msi.md)
- [Reduction transforms](reduction.md)
'''


def validate_manifest():
    """
    Verify that configured package exports are documented exactly once.
    """
    for module_name in EXPORT_MODULES:
        module = load_module(module_name)
        exported = {
            name
            for name, member in module.members.items()
            if not name.startswith('_') and member.kind.value in {'class', 'function'}
        }
        documented = {
            symbol.name
            for page in PAGES
            for symbol in page.symbols
            if symbol.module == module_name
        }
        missing = exported - documented
        extra = documented - exported
        if missing or extra:
            details = []
            if missing:
                details.append(f'missing {sorted(missing)}')
            if extra:
                details.append(f'unknown {sorted(extra)}')
            raise RuntimeError(f'Invalid API manifest for {module_name}: {"; ".join(details)}.')

    registration = load_module('imzdesk.registration')
    exported_functions = {
        name
        for name, member in registration.members.items()
        if not name.startswith('_') and member.kind.value == 'function'
    }
    documented_functions = {
        symbol.name
        for page in PAGES
        for symbol in page.symbols
        if symbol.module == 'imzdesk.registration'
    }
    if exported_functions != documented_functions:
        raise RuntimeError('The registration API manifest does not match its public functions.')


def generated_files():
    """
    Return every generated path and its expected content.
    """
    files = {
        DOCS / 'README.md': render_index(),
        DOCS / 'transforms' / 'README.md': render_transforms_index(),
    }
    files.update({DOCS / page.output: render_page(page) for page in PAGES})
    return files


def write_files(files):
    """
    Write generated documentation files to disk.
    """
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8')


def check_files(files):
    """
    Raise an error when committed API reference files are stale.
    """
    stale = [
        str(path.relative_to(ROOT))
        for path, content in files.items()
        if not path.is_file() or path.read_text(encoding='utf-8') != content
    ]
    if stale:
        paths = '\n'.join(f'- {path}' for path in stale)
        raise RuntimeError(f'Generated API documentation is stale:\n{paths}')


def main():
    """
    Generate the API reference or verify the committed output.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify that generated files are current')
    args = parser.parse_args()

    validate_manifest()
    files = generated_files()
    check_files(files) if args.check else write_files(files)


if __name__ == '__main__':
    main()
